- name: Ready... Set... Go!
  hosts: localhost
  tasks:
    - include_vars: secrets.yml

    - name: Install packages
      become: true
      package:
        name:
          - curl
          - tmux
          - feh
          - kitty
          - slack
          - i3
          - stow
          - arandr
          - zsh
          - neovim
          - fzf
          - tldr
          - xclip
   

    - name: Get oh-my-zsh
      shell:
        cmd: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"


    - name: Get dotfiles
      git:
        repo: "https://{{github_user|urlencode()}}:{{github_token|urlencode()}}@github.com/fwtn/dotfiles.git"
        dest: "~/.dotfiles"
        update: yes

    - name: Remove potentially present dotfiles
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - ~/.config/i3/config
        - ~/.config/kitty/kitty.conf
        - ~/.local/bin/cht.sh
        - ~/.local/bin/tmux-sessionizer
        - ~/.tmux.conf
        - ~/.config/nvim/init.vim
        - ~/.zshrc

    - name: Push dotfiles
      shell:
        cmd: stow
        chdir: ~/.dotfiles


    - name: Vim PLUG
      shell:
        cmd: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

    - name: Install vim plugins
      shell:
        cmd: vim +PlugInstall +qall


    - name: Update tldr cache
      shell:
        cmd: tldr -u
