- name: Ready... Set... Go!
  hosts: localhost
  tasks:
    - include_vars: secrets.yml

    - name: Install packages
      become: true
      package:
        name:
          - feh
          - kitty
          - slack
          - i3
          - stow
          - arandr
          - zsh
          - neovim
          - fzf
          - tldr
          - xclip
          - xorg
          - apt-transport-https
          - fd-find
          - ripgrep
          - sddm

    - name: Make sure local fonts directory exists
      file:
        path: ~/.local/share/fonts
        state: directory

    - name: Rustup
      shell:
        cmd: "curl https://sh.rustup.rs -sSf | sh -s -- -y"

    - name: Install lsd, bat
      shell:
        cmd: "cargo install {{ item }}"
      with_items:
        - lsd
        - bat

    - name: Get some Nerd Fonts
      shell:
        chdir: ~/.local/share/fonts
        cmd: "{{ item }}"
      with_items:
        - curl -fLo "Hack Regular Nerd Font Complete.ttf" https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Hack/Regular/complete/Hack%20Regular%20Nerd%20Font%20Complete.ttf
        - curl -fLo "Hack Bold Nerd Font Complete.ttf" https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Hack/Bold/complete/Hack%20Bold%20Nerd%20Font%20Complete.ttf
        - curl -fLo "Hack Italic Nerd Font Complete.ttf" https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Hack/Italic/complete/Hack%20Italic%20Nerd%20Font%20Complete.ttf
        - curl -fLo "Hack Bold Italic Nerd Font Complete.ttf" https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Hack/BoldItalic/complete/Hack%20Bold%20Italic%20Nerd%20Font%20Complete.ttf


    - name: Get dotfiles
      git:
        repo: "https://{{github_user|urlencode()}}:{{github_token|urlencode()}}@github.com/fwtn/dotfiles.git"
        dest: "~/.dotfiles"
        update: yes


    - name: Push dotfiles
      shell:
        cmd: stow -d ~/.dotfiles {{ item }}
      with_items:
        - i3
        - bin
        - zsh
        - tmux
        - kitty
        - nvim

    - name: Get oh-my-zsh
      shell:
        cmd: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      register: zout
      failed_when: zout.rc > 1
      changed_when: zout.rc == 0

    - name: Vim PLUG
      shell:
        cmd: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

    - name: Install vim plugins
      shell:
        cmd: vim +PlugInstall +qall


    - name: Update tldr cache
      shell:
        cmd: tldr -u

    - name: install gdm
      package:
        name: gdm3
        state: present
      become: true

    - name: Import brave apt key
      apt_key:
        url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        keyring: /usr/share/keyrings/brave-browser-stable-keyring.gpg
        state: present
      become: true

    - name: Add brave repo
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/brave-browser-stable-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"
        state: present
      become: true

    - name: Install brave
      apt:
        name: brave-browser
        state: present
        update_cache: yes
      become: true

 
    
    
    
