- name: Install zsh
  package:
    name: zsh
  become: true

- name: Set zsh as default
  shell:
    cmd: chsh -s $(which zsh)
  become: true

- name: Install oh-my-zsh
  shell:
    cmd: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  register: ohmyzsh
  failed_when: ohmyzsh.rc > 1
  changed_when: ohmyzsh.rc == 0
