- name: Install zsh
  package:
    name: zsh

- name: Set zsh as default
  shell:
    cmd: chsh -s $(which zsh)

- name: Install oh-my-zsh
  shell:
    cmd: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

